<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kosha.CustomerManager.Web.Persistence\Kosha.CustomerManager.Web.Persistence.csproj" />
  </ItemGroup>

</Project>
