<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\Layers\Domain\" />
    <Folder Include="Models\Layers\Infrastructure\" />
    <Folder Include="Models\Layers\Presentation\" />
    <Folder Include="Models\Layers\Persistence\" />
  </ItemGroup>

</Project>
